parsifal-master/parsifal/library/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url

urlpatterns = patterns('parsifal.library.views',
    url(r'^$', 'index', name='index'),
    url(r'^list_actions/$', 'list_actions', name='list_actions'),
    url(r'^new_folder/$', 'new_folder', name='new_folder'),
    url(r'^edit_folder/$', 'edit_folder', name='edit_folder'),
    url(r'^folders/(?P<slug>[-\w]+)/$', 'folder', name='folder'),
    url(r'^new_shared_folder/$', 'new_shared_folder', name='new_shared_folder'),
    url(r'^shared/(?P<slug>[-\w]+)/$', 'shared_folder', name='shared_folder'),
    url(r'^new_document/$', 'new_document', name='new_document'),
    url(r'^documents/(?P<document_id>\d+)/$', 'document', name='document'),
    url(r'^move/$', 'move', name='move'),
    url(r'^copy/$', 'copy', name='copy'),
    url(r'^remove_from_folder/$', 'remove_from_folder', name='remove_from_folder'),
    url(r'^delete_documents/$', 'delete_documents', name='delete_documents'),
    url(r'^import_bibtex/$', 'import_bibtex', name='import_bibtex'),
)

parsifal-master/parsifal/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('parsifal',
    url(r'^$', 'core.views.home', name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='core/about.html'), name='about'),
    url(r'^signup/$', 'authentication.views.signup', name='signup'),
    url(r'^signin/$', 'authentication.views.signin', name='signin'),
    url(r'^signout/$', 'authentication.views.signout', name='signout'),
    url(r'^reset/$', 'authentication.views.reset', name='reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'authentication.views.reset_confirm', name='password_reset_confirm'),
    url(r'^success/$', 'authentication.views.success', name='success'),
    url(r'^reviews/', include('parsifal.reviews.urls', namespace='reviews')),
    url(r'^activity/', include('parsifal.activities.urls', namespace='activities')),
    url(r'^blog/', include('parsifal.blog.urls', namespace='blog')),
    url(r'^help/', include('parsifal.help.urls', namespace='help')),
    url(r'^library/', include('parsifal.library.urls', namespace='library')),
    url(r'^settings/', include('parsifal.account_settings.urls', namespace='settings')),
    url(r'^review_settings/transfer/$', 'reviews.settings.views.transfer', name='transfer_review'),
    url(r'^review_settings/delete/$', 'reviews.settings.views.delete', name='delete_review'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sitemap.xml$', TemplateView.as_view(template_name='sitemap.xml', content_type='application/xml')),
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^(?P<username>[^/]+)/following/$', 'activities.views.following', name='following'),
    url(r'^(?P<username>[^/]+)/followers/$', 'activities.views.followers', name='followers'),

    # Review URLs
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/$', 'reviews.views.review', name='review'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/settings/$', 'reviews.settings.views.settings', name='settings'),
    
    # Planning Phase
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/$', 'reviews.planning.views.planning', name='planning'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/protocol/$', 'reviews.planning.views.protocol', name='protocol'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/quality/$', 'reviews.planning.views.quality_assessment_checklist', name='quality_assessment_checklist'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/planning/extraction/$', 'reviews.planning.views.data_extraction_form', name='data_extraction_form'),

    # Conducting Phase
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/$', 'reviews.conducting.views.conducting', name='conducting'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/search/$', 'reviews.conducting.views.search_studies', name='search_studies'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/import/$', 'reviews.conducting.views.import_studies', name='import_studies'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/studies/$', 'reviews.conducting.views.study_selection', name='study_selection'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/quality/$', 'reviews.conducting.views.quality_assessment', name='quality_assessment'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/extraction/$', 'reviews.conducting.views.data_extraction', name='data_extraction'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/conducting/analysis/$', 'reviews.conducting.views.data_analysis', name='data_analysis'),

    # Reporting Phase
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/reporting/$', 'reviews.reporting.views.reporting', name='reporting'),
    url(r'^(?P<username>[^/]+)/(?P<review_name>[^/]+)/reporting/export/$', 'reviews.reporting.views.export', name='export'),

    url(r'^(?P<username>[^/]+)/$', 'reviews.views.reviews', name='reviews'),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parsifal-master/parsifal/library/views.py
# coding: utf-8

import json
import os
import bibtexparser
from bibtexparser.bparser import BibTexParser
from bibtexparser.customization import convert_to_unicode

from django.db import transaction
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.core.urlresolvers import reverse as r
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.template.loader import render_to_string
from django.utils.safestring import mark_safe

from parsifal.reviews.models import Review, Article
from parsifal.library.models import Folder, Document
from parsifal.library.forms import FolderForm, DocumentForm, SharedFolderForm


def get_order(request):
    order = request.GET.get('o', '').lower()
    if order in ['title', '-title', 'author', '-author', 'year', '-year']:
        return order
    return 'title'

def get_paginated_documents(request, queryset):
    paginator = Paginator(queryset, 100)
    page = request.GET.get('p')
    try:
        documents = paginator.page(page)
    except PageNotAnInteger:
        documents = paginator.page(1)
    except EmptyPage:
        documents = paginator.page(paginator.num_pages)
    return documents

def get_filtered_documents(queryset, querystring):
    if querystring:
        queryset = queryset.filter(title__icontains=querystring)
    return queryset

def library(request, documents, querystring, order, active_folder=None):
    reviews = Review.objects.filter(author=request.user)
    folder_form = FolderForm(initial={ 'user': request.user })
    shared_folder_form = SharedFolderForm()
    current_full_path = request.get_full_path()
    return render(request, 'library/library.html', { 
            'reviews': reviews, 
            'documents': documents,
            'querystring': querystring,
            'order': order,
            'active_folder': active_folder,
            'folder_form': folder_form,
            'shared_folder_form': shared_folder_form,
            'current_full_path': current_full_path
        })

@login_required
def index(request):
    querystring = request.GET.get('q', '')
    order = get_order(request)
    queryset = Document.objects.filter(user=request.user)
    queryset = get_filtered_documents(queryset, querystring)
    queryset = queryset.order_by(order)
    documents = get_paginated_documents(request, queryset)
    return library(request, documents, querystring, order)

@login_required
@require_POST
def list_actions(request):
    action = request.POST.get('action')
    if action == 'remove_from_folder':
        return remove_from_folder(request)
    elif action == 'delete_documents':
        return delete_documents(request)
    elif action == 'move':
        return move(request)
    elif action == 'copy':
        return copy(request)
    redirect_to = request.POST.get('redirect', r('library:index'))
    return redirect(redirect_to)

@login_required
def folder(request, slug):
    querystring = request.GET.get('q', '')
    order = get_order(request)
    folder = get_object_or_404(Folder, slug=slug)
    queryset = folder.documents.all()
    queryset = get_filtered_documents(queryset, querystring)
    queryset = queryset.order_by(order)
    documents = get_paginated_documents(request, queryset)
    return library(request, documents, querystring, order, folder)

@login_required
@require_POST
def new_folder(request):
    form = FolderForm(request.POST)
    if form.is_valid():
        form.instance.user = request.user
        folder = form.save()
        dump = json.dumps({ 'folder': { 'id': folder.id, 'name': folder.name, 'slug': folder.slug } })
        return HttpResponse(dump, content_type='application/json')
    else:
        dump = json.dumps(form.errors)
        return HttpResponseBadRequest(dump, content_type='application/json')

@login_required
@require_POST
def edit_folder(request):
    delete_folder = request.POST.get('delete', '') == 'delete'
    folder_id = request.POST.get('id')
    folder = Folder.objects.get(pk=folder_id)
    if delete_folder:
        folder.delete()
        messages.success(request, u'The folder {0} was deleted successfully!'.format(folder.name))
        return redirect(r('library:index'))
    else:    
        form = FolderForm(request.POST, instance=folder)
        if form.is_valid():
            form.instance.user = request.user
            folder = form.save()
            messages.success(request, u'The folder {0} was changed successfully!'.format(folder.name))
        else:
            messages.error(request, u'An error ocurred while trying to save folder {0}'.format(folder.name))
    return redirect(r('library:folder', args=(folder.slug,)))

@login_required
def document(request, document_id):
    document = Document.objects.get(pk=document_id)
    json_context = {}
    if request.method == 'POST':
        form = DocumentForm(request.POST, instance=document)
        if form.is_valid():
            document = form.save()
            json_context['status'] = 'success'
            json_context['html'] = render_to_string('library/partial_document_summary.html', { 'document': document })
            return HttpResponse(json.dumps(json_context), content_type='application/json')
        else:
            json_context['status'] = 'error'
    else:
        form = DocumentForm(instance=document)
        json_context['status'] = 'ok'
    csrf_token = unicode(csrf(request)['csrf_token'])
    json_context['html'] = render_to_string('library/document.html', { 'form': form, 'csrf_token': csrf_token })
    return HttpResponse(json.dumps(json_context), content_type='application/json')

@login_required
def new_document(request):
    json_context = {}
    if request.method == 'POST':
        form = DocumentForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            document = form.save()
            messages.success(request, 'Document added successfully!')
            json_context['status'] = 'success'
            json_context['redirect_to'] = r('library:index')
        else:
            json_context['status'] = 'error'
    else:
        form = DocumentForm()
        json_context['status'] = 'ok'
    csrf_token = unicode(csrf(request)['csrf_token'])
    html = render_to_string('library/new_document.html', { 'form': form, 'csrf_token': csrf_token })
    json_context['html'] = html
    dump = json.dumps(json_context)
    return HttpResponse(dump, content_type='application/json')

def get_document_verbose_name(documents_size):
    document_verbose_name = 'document'
    if documents_size > 1:
        document_verbose_name = 'documents'
    return document_verbose_name

@login_required
@require_POST
def move(request):
    move_from_folder_id = request.POST.get('active-folder-id')
    move_from_folder = Folder.objects.get(pk=move_from_folder_id)

    move_to_folder_id = request.POST.get('action-folder-id')
    move_to_folder = Folder.objects.get(pk=move_to_folder_id)

    if request.POST.get('select-all-pages') == 'all':
        documents = move_from_folder.documents.all()
    else:
        document_ids = request.POST.getlist('document')
        documents = Document.objects.filter(id__in=document_ids)

    querystring = request.POST.get('querystring', '')
    documents = get_filtered_documents(documents, querystring)

    move_to_folder.documents.add(*documents)
    move_from_folder.documents.remove(*documents)

    messages.success(request, u'Documents moved from folder {0} to {1} successfully!'.format(move_from_folder.name, move_to_folder.name))
    redirect_to = request.POST.get('redirect', r('library:index'))
    return redirect(redirect_to)

@login_required
@require_POST
def copy(request):
    redirect_to = request.POST.get('redirect', r('library:index'))

    copy_from_folder_id = request.POST.get('active-folder-id')
    copy_to_folder_id = request.POST.get('action-folder-id')

    try:
        copy_to_folder = Folder.objects.get(pk=copy_to_folder_id)
    except Folder.DoesNotExist:
        messages.error(u'The folder you are trying to copy does not exist.')
        return redirect(redirect_to)

    select_all_pages = request.POST.get('select-all-pages')
    document_ids = request.POST.getlist('document')

    if copy_from_folder_id:
        try:
            copy_from_folder = Folder.objects.get(pk=copy_from_folder_id)
            documents = copy_from_folder.documents.all()
        except Folder.DoesNotExist:
            messages.error(u'The folder you are trying to copy does not exist.')
            return redirect(redirect_to)
    else:
        documents = Document.objects.filter(user=request.user)

    if select_all_pages == 'all':
        querystring = request.POST.get('querystring', '')
        documents = get_filtered_documents(documents, querystring)
    else:
        documents = documents.filter(id__in=document_ids)

    copy_to_folder.documents.add(*documents)
    messages.success(request, u'Documents copied to folder {0} successfully!'.format(copy_to_folder.name))
    return redirect(redirect_to)

@login_required
@require_POST
def remove_from_folder(request):
    remove_from_folder_id = request.POST.get('active-folder-id')
    folder = Folder.objects.get(pk=remove_from_folder_id)
    select_all_pages = request.POST.get('select-all-pages')

    if select_all_pages == 'all':
        querystring = request.POST.get('querystring', '')
        documents = folder.documents.all()
        documents = get_filtered_documents(documents, querystring)
        documents_size = documents.count()
        folder.documents.remove(*documents)
    else:
        documents = request.POST.getlist('document')
        documents_size = len(documents)
        folder.documents.remove(*documents)

parsifal-master/parsifal/library/templates/library/includes/menu.html
<div id="library-menu">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><span class="fa fa-folder-open" style="margin-right: 5px;"></span> My documents</h3>
    </div>
    <div class="list-group">
      <a href="{% url 'library:index' %}" class="list-group-item{% if active_folder == None %} active{% endif %}">All documents</a>
      {% for folder in user.library_folders.all %}
        <a href="{% url 'library:folder' folder.slug %}" class="list-group-item{% if active_folder.slug == folder.slug %} active{% endif %}">{{ folder.name }}</a>
      {% endfor %}
      <a href="javascript:void(0);" class="list-group-item js-add-folder">
        <small><span class="glyphicon glyphicon-plus"></span> Add folder…</small>
      </a>
      <a href="javascript:void(0);" class="list-group-item js-add-folder-input" style="display: none; background-color: transparent!important;">
        {% include 'library/new_folder.html' with form=folder_form %}
      </a>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><span class="fa fa-users" style="margin-right: 5px;"></span> Shared documents</h3>
    </div>
    <div class="list-group">
      {% for shared_folder in user.shared_folders.all %}
        <a href="{% url 'library:shared_folder' shared_folder.slug %}" class="list-group-item{% if active_folder.slug == shared_folder.slug %} active{% endif %}">{{ shared_folder.name }}</a>
      {% endfor %}
      <a href="javascript:void(0);" class="list-group-item js-add-shared-folder">
        <small><span class="glyphicon glyphicon-plus"></span> Add shared folder…</small>
      </a>
      <a href="javascript:void(0);" class="list-group-item js-add-shared-folder-input" style="display: none; background-color: transparent!important;">
        {% include 'library/new_shared_folder.html' with form=shared_folder_form %}
      </a>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><span class="fa fa-book" style="margin-right: 5px;"></span> Reviews</h3>
    </div>
    <div class="list-group">
      {% for review in reviews %}
        <a href="#" class="list-group-item">{{ review.title }}</a>
      {% endfor %}
    </div>
  </div>
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title"><span class="fa fa-dropbox" style="margin-right: 5px;"></span> Dropbox</h3>
    </div>
    <div class="list-group">
      <a href="#" class="list-group-item">
        <small><span class="glyphicon glyphicon-link"></span> Connect to Dropbox…</small>
      </a>
    </div>
  </div>
</div>

parsifal-master/parsifal/library/templates/library/includes/toolbar.html
<div class="btn-toolbar" id="library-toolbar" role="toolbar" aria-label="Library Toolbar">
  <div class="btn-group">
    <button type="button" class="btn btn-default btn-sm js-toggle-select-documents">
      <span class="glyphicon glyphicon-unchecked"></span>
    </button>
    <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="caret"></span>
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="javascript:void(0);" class="js-select-all-documents-in-page">All</a></li>
      <li><a href="javascript:void(0);" class="js-clear-selection">None</a></li>
    </ul>
  </div>

  <div class="btn-group not-allowed">
    <div class="btn-group">
      <button type="button" class="btn btn-default btn-sm dropdown-toggle js-selection-action" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" disabled="disabled">
        <span class="glyphicon glyphicon glyphicon-trash"></span>
        <span class="hidden-xs hidden-sm hidden-md">Delete</span>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        {% if active_folder %}
          <li><a href="javascript:void(0);" class="js-remove-from-folder" data-remote="{% url 'library:remove_from_folder' %}" data-folder-id="{{ active_folder.pk }}">Remove from folder</a></li>
        {% endif %}
        <li><a href="javascript:void(0);" class="js-delete-completely" data-remote="{% url 'library:delete_documents' %}">Delete completely</a></li>
      </ul>
    </div>

    <div class="btn-group">
      <button type="button" class="btn btn-default btn-sm dropdown-toggle js-selection-action" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" disabled="disabled">
        <span class="glyphicon glyphicon glyphicon-folder-close"></span>
        <span class="hidden-xs hidden-sm hidden-md">Organize</span>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        {% if user.library_folders.exists %}
          {% if active_folder %}
            <li role="presentation" class="dropdown-header">Move documents to…</li>
            {% for folder in user.library_folders.all %}
              {% if folder != active_folder %}
                <li><a href="javascript:void(0);" class="js-move-to" data-from-folder-id="{{ active_folder.pk }}" data-to-folder-id="{{ folder.pk }}">{{ folder.name }}</a></li>
              {% endif %}
            {% endfor %}
            <li class="divider"></li>
          {% endif %}
          <li role="presentation" class="dropdown-header">Copy documents to…</li>
          {% for folder in user.library_folders.all %}
            {% if folder != active_folder %}
              <li><a href="javascript:void(0);" class="js-copy-to" data-to-folder-id="{{ folder.pk }}">{{ folder.name }}</a></li>
            {% endif %}
          {% endfor %}
        {% else %}
          <li class="dropdown-header"><em>Your library has no folder yet</em></li>
        {% endif %}
      </ul>
    </div>
  </div>

  <div class="btn-group">
    <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="glyphicon glyphicon-option-horizontal visible-xs-inline visible-sm-inline visible-md-inline"></span>
      <span class="hidden-xs hidden-sm hidden-md">More</span>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="#">Export all as bibtex</a></li>
      <li class="divider"></li>
      <li class="dropdown-header"><em>Select documents to<br>see more options</em></li>
    </ul>
  </div>

  {% if active_folder %}
    <div class="btn-group pull-right">
      <a href="javascript:void(0);" class="btn btn-sm btn-default" data-toggle="modal" data-target="#modal-folder-settings">
        <span class="glyphicon glyphicon-cog"></span>
        <span class="hidden-xs hidden-sm hidden-md">Settings</span>
      </a>
    </div>
  {% endif %}

  <div class="btn-group pull-right" role="group" aria-label="Pager">
    {% if documents.has_previous %}
      <a href="?p={{ documents.previous_page_number }}{% if order %}&o={{ order }}{% endif %}{% if querystring %}&q={{ querystring }}{% endif %}" class="btn btn-default btn-sm">
        <span class="glyphicon glyphicon-arrow-left"></span>
      </a>
    {% else %}
      <button type="button" class="btn btn-default btn-sm" disabled>
        <span class="glyphicon glyphicon-arrow-left"></span>
      </button>
    {% endif %}
    {% if documents.has_next %}
      <a href="?p={{ documents.next_page_number }}{% if order %}&o={{ order }}{% endif %}{% if querystring %}&q={{ querystring }}{% endif %}" class="btn btn-default btn-sm">
        <span class="glyphicon glyphicon-arrow-right"></span>
      </a>
    {% else %}
      <button type="button" class="btn btn-default btn-sm" disabled>
        <span class="glyphicon glyphicon-arrow-right"></span>
      </button>
    {% endif %}
  </div>

  <div class="btn-group pull-right">
    <a href="javascript:void(0);" class="btn btn-sm btn-link library-documents-indexes js-jump-page" data-container="body" data-placement="bottom">
      <strong>{{ documents.start_index }}</strong> – <strong>{{ documents.end_index }}</strong> of <strong>{{ documents.paginator.count }}</strong>
    </a>
  </div>

  <div class="btn-group pull-right">
    <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="glyphicon glyphicon-sort-by-attributes"></span>
      <span class="hidden-xs hidden-sm hidden-md">Sort</span>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li{% if order == 'title' %} class="active"{% endif %}><a href="?o=title{% if querystring %}&q={{ querystring }}{% endif %}">Title (a - z)</a></li>
      <li{% if order == '-title' %} class="active"{% endif %}><a href="?o=-title{% if querystring %}&q={{ querystring }}{% endif %}">Title (z - a)</a></li>
      <li{% if order == 'author' %} class="active"{% endif %}><a href="?o=author{% if querystring %}&q={{ querystring }}{% endif %}">Author (a - z)</a></li>
      <li{% if order == '-author' %} class="active"{% endif %}><a href="?o=-author{% if querystring %}&q={{ querystring }}{% endif %}">Author (z - a)</a></li>
      <li{% if order == 'year' %} class="active"{% endif %}><a href="?o=year{% if querystring %}&q={{ querystring }}{% endif %}">Publication year (0 - 9)</a></li>
      <li{% if order == '-year' %} class="active"{% endif %}><a href="?o=-year{% if querystring %}&q={{ querystring }}{% endif %}">Publication year (9 - 0)</a></li>
    </ul>
  </div>

  <div class="btn-group pull-right">
    <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="glyphicon glyphicon-plus"></span>
      <span class="hidden-xs hidden-sm hidden-md">Add</span>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="javascript:void(0);" class="js-import-bibtex">BibTeX <small>(.bib, .bibtex)</small></a></li>
      <li><a href="#">PDF <small>(.pdf)</small></a></li>
      <li class="divider"></li>
      <li><a href="javascript:void(0);" class="js-new-document">Add document</a></li>
    </ul>
  </div>

</div>

<form id="form-import-bibtex" method="post" action="{% url 'library:import_bibtex' %}" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="hidden" name="add-to-folder-id" value="{{ active_folder.pk }}">
  <input type="hidden" name="redirect" value="{{ request.path }}">
  <input id="input-bibtex" type="file" name="bibtex" style="display: none;">
</form>